x= int(input("Number 1 :"))
y=int(input("Number 2 :"))

print("Sum : ",x+y)
print("Diffrence : ",x-y)
print("Product : ",x*y)
print("Quotient : ",x/y)
print("Floor Division : ",x//y)
print("Remainder : " ,x%y)
print("Power : ", x**y)
